-- 테이블 삭제 
DROP TABLE MCARE_ACCESS_HISTORY; 
DROP TABLE MCARE_LOGIN_HISTORY; 
DROP TABLE MCARE_AGG_ACCESS; 
DROP TABLE MCARE_AGG_DAILY; 
DROP TABLE MCARE_AGG_HOURLY; 
DROP TABLE MCARE_AGG_PLATFORM; 
DROP TABLE MCARE_API_PARAM; 
DROP TABLE MCARE_API_HEADER; 
DROP TABLE MCARE_API; 
DROP TABLE MCARE_API_CATEGORY; 
DROP TABLE MCARE_I18N; 
DROP TABLE MCARE_VERSION; 
DROP TABLE MCARE_MANAGER; 
DROP TABLE MNS_RECEIVER_DEVICE; 
DROP TABLE MNS_RECEIVER_RESULT; 
DROP TABLE MNS_RECEIVER; 
DROP TABLE MNS_CONTENTS_RESULT; 
DROP TABLE MNS_CONTENTS; 
DROP TABLE MCARE_TELNO; 
DROP TABLE MCARE_USER_AGREEMENT; 
DROP TABLE MCARE_AGREEMENT; 
DROP TABLE MCARE_USER; 
DROP TABLE MCARE_HELPER_CONTENTS; 
DROP TABLE MCARE_PUSH_FORM; 
DROP TABLE MCARE_AGG_MSG; 
DROP TABLE MCARE_MENU_PARAM; 
DROP TABLE MCARE_MENU; 
DROP TABLE MCARE_EVENT_LOG; 
DROP TABLE MCARE_AGG_EVENT; 
DROP TABLE MCARE_POI_MAPPING; 
DROP TABLE MCARE_MNS_MSGMAPPING;
DROP TABLE MCARE_AGG_USER_AGE; 
DROP TABLE MCARE_AGG_USER_POSTNO; 
DROP TABLE MCARE_AGG_USER_TMP;
DROP TABLE MCARE_ZIPCODE;
DROP TABLE MCARE_INF_PUSH_MSG;
DROP TABLE MCARE_AGG_USER_REGISTER; 
DROP TABLE MCARE_USER_WITHDRAWAL; 
COMMIT; 

-- 시퀀스 삭제 
DROP SEQUENCE SEQ_MCARE_ACCESS_HISTORY_HS; 
DROP SEQUENCE SEQ_MCARE_AGG_ACCESS_AS; 
DROP SEQUENCE SEQ_MCARE_AGG_DAILY_DS; 
DROP SEQUENCE SEQ_MCARE_AGG_HOURLY_HS; 
DROP SEQUENCE SEQ_MCARE_AGG_PLATFORM_PS; 
DROP SEQUENCE SEQ_MCARE_API_AS; 
DROP SEQUENCE SEQ_MCARE_API_CATEGORY_CS; 
DROP SEQUENCE SEQ_MCARE_API_HEADER_HS; 
DROP SEQUENCE SEQ_MCARE_API_PARAM_PS; 
DROP SEQUENCE SEQ_MCARE_LOGIN_HISTORY_LS; 
DROP SEQUENCE SEQ_MCARE_AGREEMENT; 
DROP SEQUENCE SEQ_MCARE_TELNO_TS; 
DROP SEQUENCE SEQ_MNS_CONTENTS; 
DROP SEQUENCE SEQ_MCARE_USER_AGREEMENT_UA; 
DROP SEQUENCE SEQ_MCARE_USER_US; 
DROP SEQUENCE SEQ_MCARE_HELPER_HS; 
DROP SEQUENCE SEQ_MCARE_POI_PS; 
DROP SEQUENCE SEQ_MCARE_EVENT_LOG_LS; 
DROP SEQUENCE SEQ_MCARE_AGG_EVENT_AS; 
DROP SEQUENCE SEQ_MCARE_AGG_MSG_MS; 
DROP SEQUENCE SEQ_MCARE_INF_FORM_PUSH_PS; 
DROP SEQUENCE SEQ_MCARE_MENU_PARAM_SEQ_MPS; 
DROP SEQUENCE SEQ_MCARE_AGG_USER_AU; 
DROP SEQUENCE SEQ_MCARE_AGG_POSTNO_AP; 
DROP SEQUENCE SEQ_MCARE_ZIPCODE_ZC; 
DROP SEQUENCE SEQ_MCARE_INF_FORM_PUSH_PS;
DROP SEQUENCE SEQ_MCARE_USER_REGISTER_UR; 
COMMIT;   

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_ACCESS_HISTORY 
(
	HISTORY_SEQ NUMBER(20,0) DEFAULT 0, 
	P_ID 	VARCHAR2 (255),
---	DEVICE_UUID_ID VARCHAR2(255), 
	MENU_ID VARCHAR2(255), 
	MENU_NAME VARCHAR2(255), 
	REQ_URI_ADDR VARCHAR2(1024), 
	REMOTE_IP_ADDR VARCHAR2(1024), 
	ACCESS_DT DATE, 
	PLATFORM_TYPE VARCHAR2(50), 
	BROWSER_VALUE VARCHAR2(255), 
	SERVER_IP_ADDR VARCHAR2(1024),
	ACCESS_HASH_VALUE VARCHAR2(255) 
);
CREATE SEQUENCE SEQ_MCARE_ACCESS_HISTORY_HS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.HISTORY_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.P_ID  IS '환자식별자'; 
--- COMMENT ON COLUMN MCARE_ACCESS_HISTORY.DEVICE_UUID_ID  IS '장비 고유식별자 or IP'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.MENU_ID  IS 'access원하는 메뉴식별자'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.MENU_NAME  IS 'access원하는 메뉴명 (메뉴가 동적으로 바뀔 수 있으므로 이름백업)'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.REQ_URI_ADDR  IS 'access 주소 (ui의 action)'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.REMOTE_IP_ADDR  IS 'client의 ip'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.ACCESS_DT  IS '요청일시'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.PLATFORM_TYPE  IS 'http 요청의 user agent 분석을 통해 결정되는 플랫폼 유형'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.BROWSER_VALUE  IS 'http 요청의 user agent 분석을 통해 결정되는 브라우저 유형'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.SERVER_IP_ADDR  IS '서버주소'; 
COMMENT ON COLUMN MCARE_ACCESS_HISTORY.ACCESS_HASH_VALUE  IS '접근이력 위변조 방지용'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_AGG_ACCESS 
(	
  	ACCESS_SEQ NUMBER(20,0), 
	MENU_ID VARCHAR2(255), 
	MENU_NAME VARCHAR2(255), 
	REQ_URI_ADDR VARCHAR2(1024), 
	HIT_CNT NUMBER(*,0), 
	AGG_DT DATE, 
	CONSTRAINT UQ_ACCESS_DT_MENU_ID UNIQUE (AGG_DT, MENU_ID)
); 
CREATE SEQUENCE SEQ_MCARE_AGG_ACCESS_AS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_AGG_ACCESS.ACCESS_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_ACCESS.MENU_ID  IS '메뉴ID'; 
COMMENT ON COLUMN MCARE_AGG_ACCESS.MENU_NAME  IS '메뉴명'; 
COMMENT ON COLUMN MCARE_AGG_ACCESS.REQ_URI_ADDR  IS 'access 주소 (ui의 action)'; 
COMMENT ON COLUMN MCARE_AGG_ACCESS.HIT_CNT  IS '방문횟수'; 
COMMENT ON COLUMN MCARE_AGG_ACCESS.AGG_DT  IS '통계일시 (이 시간에 해당 메뉴에 얼마나 방문했는지)'; 
 
---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_AGG_DAILY 
(	
   	DAILY_SEQ NUMBER(20,0), 
	AGG_DT DATE, 
	HIT_CNT NUMBER(*,0), 
	WEEK_ORDER NUMBER(*,0), 
	CONSTRAINT UQ_AGG_DT_WEEK_ORDER UNIQUE (AGG_DT, WEEK_ORDER)
);
CREATE SEQUENCE SEQ_MCARE_AGG_DAILY_DS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_AGG_DAILY.DAILY_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_DAILY.AGG_DT  IS '통계일시 (이 시간에 해당 메뉴에 얼마나 방문했는지)'; 
COMMENT ON COLUMN MCARE_AGG_DAILY.HIT_CNT  IS '방문횟수'; 
COMMENT ON COLUMN MCARE_AGG_DAILY.WEEK_ORDER  IS '무슨요일인지'; 
   
---------------------------------------------------------------------------------------------- 
   
CREATE TABLE MCARE_AGG_HOURLY 
(	
	HOURLY_SEQ NUMBER(20,0), 
	AGG_DT DATE, 
	HIT_CNT NUMBER(*,0), 
	TIME_ORDER NUMBER(*,0), 
	CONSTRAINT UQ_AGG_DT_TIME_ORDER UNIQUE (AGG_DT, TIME_ORDER)
); 
CREATE SEQUENCE SEQ_MCARE_AGG_HOURLY_HS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807  NOORDER;
COMMENT ON COLUMN MCARE_AGG_HOURLY.HOURLY_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_HOURLY.AGG_DT  IS '통계일시 (이 시간에 해당 메뉴에 얼마나 방문했는지)'; 
COMMENT ON COLUMN MCARE_AGG_HOURLY.HIT_CNT  IS '방문횟수'; 
COMMENT ON COLUMN MCARE_AGG_HOURLY.TIME_ORDER  IS '몇시인지'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_AGG_PLATFORM 
(	
	PLATFORM_SEQ NUMBER(20,0), 
	PLATFORM_TYPE VARCHAR2(50), 
	HIT_CNT NUMBER(*,0), 
	AGG_DT DATE, 
	CONSTRAINT UQ_AGG_DT_PLATFROM_TYPE UNIQUE (AGG_DT, PLATFORM_TYPE)
); 
CREATE SEQUENCE SEQ_MCARE_AGG_PLATFORM_PS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;  
COMMENT ON COLUMN MCARE_AGG_PLATFORM.PLATFORM_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_PLATFORM.PLATFORM_TYPE  IS '플랫폼'; 
COMMENT ON COLUMN MCARE_AGG_PLATFORM.AGG_DT  IS '통계일시 (이 시간에 해당 메뉴에 얼마나 방문했는지)'; 
COMMENT ON COLUMN MCARE_AGG_PLATFORM.HIT_CNT  IS '방문횟수'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_API_CATEGORY 
(	
    CAT_SEQ NUMBER(20,0), 
	CAT_NAME VARCHAR2(255), 
	CAT_DESC VARCHAR2(500), 
	PARENT_CAT_SEQ NUMBER(20,0), 
	PATH_NAME VARCHAR2(255), 
	CREATE_DT DATE, 
	CREATE_ID VARCHAR2(255), 
	UPDATE_DT DATE, 
	UPDATE_ID VARCHAR2(255), 
	CONSTRAINT PK_MCARE_API_CATEGORY PRIMARY KEY (CAT_SEQ), 
	CONSTRAINT UQ_API_CAT_PATH_NAME UNIQUE(PATH_NAME)
); 
CREATE SEQUENCE SEQ_MCARE_API_CATEGORY_CS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;    
COMMENT ON COLUMN MCARE_API_CATEGORY.CAT_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.CAT_NAME  IS '카테고리명'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.CAT_DESC  IS '설명'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.PARENT_CAT_SEQ  IS '부모 시퀀스'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.PATH_NAME  IS '카테고리 경로';   
COMMENT ON COLUMN MCARE_API_CATEGORY.CREATE_DT  IS '생성일시'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.CREATE_ID  IS '생성자'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.UPDATE_DT  IS '수정일시'; 
COMMENT ON COLUMN MCARE_API_CATEGORY.UPDATE_ID  IS '수정자';  

---------------------------------------------------------------------------------------------- 
   
CREATE TABLE MCARE_API 
(	
    API_SEQ NUMBER(20,0), 
	API_TYPE VARCHAR2(50), 
	DATA_SOURCE_NAME VARCHAR2(255), 
	API_DESC VARCHAR2(500), 
	HTTP_METHOD_TYPE VARCHAR2(50), 
	API_NAME VARCHAR2(255), 
	TARGET_NAME VARCHAR2(255), 
	QUERY_MSG VARCHAR2(2048), 
	RESULT_TYPE VARCHAR2(50), 
	REQ_URL_ADDR VARCHAR2(1024), 
	--- REQ_URL_NAME VARCHAR2(255), 
	TARGET_URL_ADDR VARCHAR2(1024), 
	CAT_SEQ NUMBER(20,0), 
	--- CAT_NAME VARCHAR2(255), 
	CAT_PATH_NAME VARCHAR2(255), 
	CREATE_DT DATE, 
	CREATE_ID VARCHAR2(255), 
	UPDATE_DT DATE, 
	UPDATE_ID VARCHAR2(255), 
	CONSTRAINT PK_MCARE_API PRIMARY KEY (API_SEQ),
	CONSTRAINT UQ_API_CAT_SEQ UNIQUE (CAT_PATH_NAME, REQ_URL_ADDR),
	CONSTRAINT FK_API_CAT_SEQ FOREIGN KEY (CAT_SEQ) REFERENCES MCARE_API_CATEGORY (CAT_SEQ)
);  
CREATE SEQUENCE SEQ_MCARE_API_AS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MCARE_API.API_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_API.API_TYPE  IS '유형 (SQL, WEB SERVICE..)'; 
COMMENT ON COLUMN MCARE_API.DATA_SOURCE_NAME  IS 'SQL타입인 경우 사용할 DataSource명'; 
COMMENT ON COLUMN MCARE_API.API_DESC  IS '설명'; 
COMMENT ON COLUMN MCARE_API.HTTP_METHOD_TYPE  IS 'HTTP통신이 사용되는 경우 메소드 유형 (GET/PUT/POST/DELETE)'; 
COMMENT ON COLUMN MCARE_API.API_NAME  IS '이름'; 
COMMENT ON COLUMN MCARE_API.TARGET_NAME  IS '프로시저명'; 
COMMENT ON COLUMN MCARE_API.QUERY_MSG  IS 'DB연동인 경우 질의문'; 
COMMENT ON COLUMN MCARE_API.RESULT_TYPE  IS '결과유형 (MAP, LIST, INT..)'; 
COMMENT ON COLUMN MCARE_API.REQ_URL_ADDR  IS '요청과 맵핑되는 주소 (category가 제외된 형태)'; 
COMMENT ON COLUMN MCARE_API.REQ_URL_NAME  IS '삭제예정'; 
COMMENT ON COLUMN MCARE_API.TARGET_URL_ADDR  IS 'HTTP 통신인 경우, API가 호출해야 하는 상대편 웹 서비스 주소 (파라미터 포함)'; 
COMMENT ON COLUMN MCARE_API.CAT_SEQ  IS 'API가 어느 카테고리에 포함되는지 시퀀스'; 
COMMENT ON COLUMN MCARE_API.CAT_NAME  IS 'API가 포함되는 카테고리 명 (반정규화)'; 
COMMENT ON COLUMN MCARE_API.CAT_PATH_NAME  IS 'API가 포함되는 카테고리 경로명 (반정규화)'; 
COMMENT ON COLUMN MCARE_API.CREATE_DT  IS '생성일시'; 
COMMENT ON COLUMN MCARE_API.CREATE_ID  IS '생성자'; 
COMMENT ON COLUMN MCARE_API.UPDATE_DT  IS '수정일시'; 
COMMENT ON COLUMN MCARE_API.UPDATE_ID  IS '수정자'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_API_HEADER 
(	
    HEADER_SEQ NUMBER(20,0), 
	API_SEQ NUMBER(20,0), 
	HEADER_NAME VARCHAR2(255), 
	HEADER_VALUE VARCHAR2(255),
	CONSTRAINT FK_API_HEADER_API_SEQ FOREIGN KEY (API_SEQ) REFERENCES MCARE_API (API_SEQ)
); 
CREATE SEQUENCE SEQ_MCARE_API_HEADER_HS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MCARE_API_HEADER.HEADER_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_API_HEADER.API_SEQ  IS '어떤 API의 헤더인지에 대한 시퀀스';
COMMENT ON COLUMN MCARE_API_HEADER.HEADER_NAME  IS '헤더명';
COMMENT ON COLUMN MCARE_API_HEADER.HEADER_VALUE  IS '헤더값';

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_API_PARAM 
(	
    PARAM_SEQ NUMBER(20,0), 
	API_SEQ NUMBER(20,0), 
	DATA_TYPE VARCHAR2(50), 
	PARAM_DESC VARCHAR2(500), 
	PARAM_NAME VARCHAR2(255), 
	SAMPLE_VALUE VARCHAR2(4000),
	CONSTRAINT FK_API_PARAM_API_SEQ FOREIGN KEY (API_SEQ) REFERENCES MCARE_API (API_SEQ)
); 
CREATE SEQUENCE SEQ_MCARE_API_PARAM_PS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MCARE_API_PARAM.PARAM_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_API_PARAM.API_SEQ  IS '어떤 API에 대한 파라미터인지'; 
COMMENT ON COLUMN MCARE_API_PARAM.DATA_TYPE  IS '파라미터의 데이터 타입'; 
COMMENT ON COLUMN MCARE_API_PARAM.PARAM_DESC  IS '설명'; 
COMMENT ON COLUMN MCARE_API_PARAM.PARAM_NAME  IS '이름'; 
COMMENT ON COLUMN MCARE_API_PARAM.SAMPLE_VALUE  IS '샘플 값'; 
 
---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_MENU 
(	
	MENU_ID VARCHAR2(255), 
	PARENT_MENU_ID VARCHAR2(255), 
	MENU_ORDER NUMBER(*,0), 
	MENU_TYPE VARCHAR2(50) DEFAULT 'MAIN', 
	MENU_NAME VARCHAR2(255), 
	ENABLED_YN CHAR(1) DEFAULT 'N', 
	ACCESS_URI_ADDR VARCHAR2(1024), 
	IMAGE_URI_ADDR VARCHAR2(1024), 
	MENU_DESC VARCHAR2(500), 
	AUTH_YN CHAR(1) DEFAULT 'Y', 
	AUTH_VIEW_YN CHAR(1) DEFAULT 'N', 
	AGG_YN CHAR(1) DEFAULT 'N', 
	CONSTRAINT PK_MCARE_MENU PRIMARY KEY (MENU_ID)
); 
COMMENT ON COLUMN MCARE_MENU.MENU_ID  IS '식별자'; 
COMMENT ON COLUMN MCARE_MENU.PARENT_MENU_ID  IS '부모메뉴 식별자'; 
COMMENT ON COLUMN MCARE_MENU.MENU_ORDER  IS '표시순서'; 
COMMENT ON COLUMN MCARE_MENU.MENU_TYPE  IS '메뉴유형 (NAVI, SIDE, CONT..)'; 
COMMENT ON COLUMN MCARE_MENU.MENU_NAME  IS '메뉴명 (사용자가 보는 text)'; 
COMMENT ON COLUMN MCARE_MENU.ENABLED_YN  IS '사용되는지 여부'; 
COMMENT ON COLUMN MCARE_MENU.ACCESS_URI_ADDR  IS '접근주소'; 
COMMENT ON COLUMN MCARE_MENU.IMAGE_URI_ADDR  IS '이미지 주소'; 
COMMENT ON COLUMN MCARE_MENU.MENU_DESC  IS '설명'; 
COMMENT ON COLUMN MCARE_MENU.AUTH_YN  IS '로그인한 사용자만 쓰는지 여부'; 
COMMENT ON COLUMN MCARE_MENU.AUTH_VIEW_YN  IS '로그인한 사용자에게 보일지 여부'; 
COMMENT ON COLUMN MCARE_MENU.AGG_YN  IS '통계대상인지 여부 '; 

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_MENU_PARAM 
(
	MENU_PARAM_SEQ NUMBER(20,0), 	
	MENU_ID VARCHAR2(255), 
	PARAM_NAME VARCHAR2(255) NOT NULL, 
	DATA_TYPE VARCHAR2(50) NOT NULL, 
	PARAM_VALUE VARCHAR2(4000), 
	PARAM_DESC VARCHAR2(500), 
	CONSTRAINT FK_PARAM_MENU_ID FOREIGN KEY(MENU_ID) REFERENCES MCARE_MENU(MENU_ID), 
	CONSTRAINT UQ_PARAM_PARAM_NAME UNIQUE (MENU_ID, PARAM_NAME)
);   
CREATE SEQUENCE SEQ_MCARE_MENU_PARAM_SEQ_MPS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MCARE_MENU_PARAM.MENU_PARAM_SEQ IS '파라미터 SEQ'; 
COMMENT ON COLUMN MCARE_MENU_PARAM.MENU_ID IS '메뉴 ID'; 
COMMENT ON COLUMN MCARE_MENU_PARAM.PARAM_NAME IS '파라미터명'; 
COMMENT ON COLUMN MCARE_MENU_PARAM.DATA_TYPE IS '데이터 타입'; 
COMMENT ON COLUMN MCARE_MENU_PARAM.PARAM_VALUE IS '파라미터 값'; 
COMMENT ON COLUMN MCARE_MENU_PARAM.PARAM_DESC IS '파라미터 설명'; 

----------------------------------------------------------------------------------------------

CREATE TABLE MCARE_I18N 
(	
    MENU_ID VARCHAR2(255), 
	I18N_CD CHAR(2), 
	CD_TEXT VARCHAR2(255),
	CONSTRAINT UQ_I18N_MENU_ID_I18N_CD UNIQUE (MENU_ID, I18N_CD), 
	CONSTRAINT FK_I18N_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES MCARE_MENU (MENU_ID)
);
COMMENT ON COLUMN MCARE_I18N.MENU_ID  IS '메뉴 ID';     
COMMENT ON COLUMN MCARE_I18N.I18N_CD  IS '언어코드'; 
COMMENT ON COLUMN MCARE_I18N.CD_TEXT  IS '코드에 대핟되는 문자열'; 

---------------------------------------------------------------------------------------------- 
  
CREATE TABLE MCARE_LOGIN_HISTORY 
(	
    LOGIN_SEQ NUMBER(20,0), 
	USER_ID VARCHAR2(255), 
	LOGIN_DT DATE, 
	REMEMBER_ME_YN CHAR(1),
	LOGIN_HASH_VALUE VARCHAR2 (255)
); 
CREATE SEQUENCE SEQ_MCARE_LOGIN_HISTORY_LS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MCARE_LOGIN_HISTORY.LOGIN_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_LOGIN_HISTORY.USER_ID  IS '사용자 ID'; 
COMMENT ON COLUMN MCARE_LOGIN_HISTORY.LOGIN_DT  IS '로그인 일시'; 
COMMENT ON COLUMN MCARE_LOGIN_HISTORY.REMEMBER_ME_YN  IS '자동 로그인 여부'; 
COMMENT ON COLUMN MCARE_LOGIN_HISTORY.LOGIN_HASH_VALUE  IS '로그인 해쉬'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_MANAGER 
(	
    USER_ID VARCHAR2(255), 
	USER_NAME VARCHAR2(255), 
	ENABLED_YN CHAR(1) DEFAULT 'N', 
	DEPT_NAME VARCHAR2(255), 
	PWD_VALUE VARCHAR2(255), 
	CREATE_DT DATE, 
	CREATE_ID VARCHAR2(255), 
	UPDATE_DT DATE, 
	UPDATE_ID VARCHAR2(255), 
	CONSTRAINT PK_MCARE_MANAGER PRIMARY KEY (USER_ID)
); 
COMMENT ON COLUMN MCARE_MANAGER.USER_ID  IS '로그인 ID'; 
COMMENT ON COLUMN MCARE_MANAGER.USER_NAME  IS '이름'; 
COMMENT ON COLUMN MCARE_MANAGER.ENABLED_YN  IS '활성화 여부'; 
COMMENT ON COLUMN MCARE_MANAGER.PWD_VALUE  IS '로그인 암호'; 
COMMENT ON COLUMN MCARE_MANAGER.CREATE_DT  IS '생성일시'; 
COMMENT ON COLUMN MCARE_MANAGER.CREATE_ID  IS '생성자'; 
COMMENT ON COLUMN MCARE_MANAGER.UPDATE_DT  IS '수정일시'; 
COMMENT ON COLUMN MCARE_MANAGER.UPDATE_ID  IS '수정자';  
   
---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_VERSION 
(	
    PLATFORM_TYPE 	VARCHAR2(50), 
    CERT_TYPE 		VARHCAR2(50) DEFAULT 'InHouse', 
	VERSION_ORDER 	NUMBER(*,0), 
	APP_NAME 		VARCHAR2(255), 
	MARKET_URL 		VARCHAR2(1024) 
	CONSTRAINT UQ_MCARE_VERSION UNIQUE (PLATFORM_TYPE, CERT_TYPE, APP_NAME) 
); 
COMMENT ON COLUMN MCARE_VERSION.PLATFORM_TYPE  IS '플랫폼 유형';
COMMENT ON COLUMN MCARE_VERSION.CERT_TYPE	IS '인증유형 구분 (InHouse, AppStore 등..)';
COMMENT ON COLUMN MCARE_VERSION.VERSION_ORDER  IS '현재 최신버전. 이 버전보다 이전 버전들은 업데이트를 해야함. 이후버전(지금 심사중인 버전)들은 안해도됨. ';
COMMENT ON COLUMN MCARE_VERSION.APP_NAME  IS '배포된 이름';
COMMENT ON COLUMN MCARE_VERSION.MARKET_URL  IS '앱을 다운로드 받기 위한 마켓 주소';

---------------------------------------------------------------------------------------------- 

   
CREATE TABLE MNS_RECEIVER_DEVICE 
(	
	RECEIVER_ID 	VARCHAR2(255) NOT NULL, 
	DEVICE_TOKEN_ID VARCHAR2(255), 
	PLATFORM_TYPE 	VARCHAR2(50) NOT NULL,
	CERT_TYPE 		VARCHAR2(50) DEFAULT '',
	REGISTER_DT 	DATE DEFAULT SYSDATE, 
	UPDATE_DT 		DATE DEFAULT SYSDATE, 
	CONSTRAINT UQ_RECEIVER_TOKEN_ID UNIQUE (RECEIVER_ID, DEVICE_TOKEN_ID, PLATFORM_TYPE, CERT_TYPE)
); 
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.RECEIVER_ID  IS '수신자 아이디 (예 : 사용자ID)';
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.DEVICE_TOKEN_ID  IS '토큰';
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.PLATFORM_TYPE  IS '플랫폼 구분 (A : Android, I : iPhone)'; 
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.CERT_TYPE	IS '인증유형 구분 (InHouse, AppStore 등..)';
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.REGISTER_DT  IS '토큰 등록일';
COMMENT ON COLUMN MNS_RECEIVER_DEVICE.UPDATE_DT  IS '토큰 수정일';
---------------------------------------------------------------------------------------------- 

CREATE TABLE MNS_CONTENTS 
(	
	CONTENTS_SEQ NUMBER(20,0), 
	CONTENTS_MSG VARCHAR2(4000) NOT NULL, 
	SENDER_ID VARCHAR2(100) NOT NULL, 
	CREATE_DT DATE DEFAULT SYSDATE, 
	RESERVE_SEND_DT DATE DEFAULT SYSDATE, 
	CONSTRAINT PK_MNS_CONTENTS PRIMARY KEY (CONTENTS_SEQ)
); 
CREATE SEQUENCE SEQ_MNS_CONTENTS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;   
COMMENT ON COLUMN MNS_CONTENTS.CONTENTS_SEQ  IS '시퀀스';
COMMENT ON COLUMN MNS_CONTENTS.CONTENTS_MSG  IS '메시지 내용';
COMMENT ON COLUMN MNS_CONTENTS.SENDER_ID  IS '발송자아이디';
COMMENT ON COLUMN MNS_CONTENTS.CREATE_DT  IS '레코드 등록일시';
COMMENT ON COLUMN MNS_CONTENTS.RESERVE_SEND_DT  IS '예약전송일시';

---------------------------------------------------------------------------------------------- 

CREATE TABLE MNS_CONTENTS_RESULT 
(	
	CONTENTS_SEQ NUMBER(20,0), 
	COMPLETE_DT DATE NOT NULL,
	CONSTRAINT FK_CONTENTS_SEQ FOREIGN KEY (CONTENTS_SEQ) REFERENCES MNS_CONTENTS (CONTENTS_SEQ), 
	CONSTRAINT UQ_CONTENTS_SEQ UNIQUE (CONTENTS_SEQ)
); 
COMMENT ON COLUMN MNS_CONTENTS_RESULT.CONTENTS_SEQ  IS '발송순서'; 
COMMENT ON COLUMN MNS_CONTENTS_RESULT.COMPLETE_DT  IS '전체 수신자에 대한 발송완료 일시'; 
  
---------------------------------------------------------------------------------------------- 
 
CREATE TABLE MNS_RECEIVER 
(	
	CONTENTS_SEQ NUMBER(20,0) , 
	RECEIVER_ID VARCHAR2(255) NOT NULL,
	CONSTRAINT FK_RC_CONTENTS_SEQ FOREIGN KEY (CONTENTS_SEQ) REFERENCES MNS_CONTENTS (CONTENTS_SEQ), 
	CONSTRAINT UQ_RC_CONTENTS_SEQ_RECEIVER_ID UNIQUE (CONTENTS_SEQ, RECEIVER_ID) VALIDATE
); 
COMMENT ON COLUMN MNS_RECEIVER.CONTENTS_SEQ  IS '발송순서';   
COMMENT ON COLUMN MNS_RECEIVER.RECEIVER_ID  IS '수신자 아이디';   

---------------------------------------------------------------------------------------------- 

CREATE TABLE MNS_RECEIVER_RESULT 
(	
	CONTENTS_SEQ NUMBER(20,0), 
	RECEIVER_ID VARCHAR2(255), 
	DEVICE_TOKEN_ID VARCHAR2(255), 
	PLATFORM_TYPE VARCHAR2(50), 
	SEND_DT DATE NOT NULL, 
	SUCCESS_YN CHAR(1) NOT NULL, 
	ERROR_TYPE VARCHAR2(50), 
	DELETE_YN CHAR(1), 
	READ_YN CHAR(1),
	CONSTRAINT FK_CONTENTS_SEQ_RECEIVER_ID FOREIGN KEY (CONTENTS_SEQ, RECEIVER_ID)
          REFERENCES MNS_RECEIVER (CONTENTS_SEQ, RECEIVER_ID)
);  
COMMENT ON COLUMN MNS_RECEIVER_RESULT.CONTENTS_SEQ  IS '발송순서';  
COMMENT ON COLUMN MNS_RECEIVER_RESULT.RECEIVER_ID  IS '수신자 아이디'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.DEVICE_TOKEN_ID  IS '토큰';   
COMMENT ON COLUMN MNS_RECEIVER_RESULT.PLATFORM_TYPE  IS '플랫폼 구분'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.SEND_DT  IS '발송일시'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.SUCCESS_YN  IS '발송 성공여부'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.ERROR_TYPE  IS '발송실패 에러응답코드'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.DELETE_YN  IS '메시지 삭제여부 (삭제예정필드)'; 
COMMENT ON COLUMN MNS_RECEIVER_RESULT.READ_YN  IS '메시지 읽음여부 (삭제예정필드)'; 

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_USER
(
   USER_SEQ                 NUMBER (20),
   P_ID            			VARCHAR2 (255),
---   P_NAME               	VARCHAR2 (255),
   LOGIN_FAIL_CNT           NUMBER (10),
   PASSWORD_VALUE           VARCHAR2 (255),
   PASSWORD_UPDATE_DT       DATE,
   REGISTER_DT              DATE,
   LOCAL_CIPHER_KEY_VALUE   VARCHAR2 (255),
   CONSTRAINT PK_P_ID PRIMARY KEY (P_ID)
); 

CREATE SEQUENCE SEQ_MCARE_USER_US INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER; 
COMMENT ON COLUMN MCARE_USER.USER_SEQ IS '시퀀스'; 
COMMENT ON COLUMN MCARE_USER.P_ID IS '챠트번호(환자번호)'; 
--- COMMENT ON COLUMN MCARE_USER.P_NAME IS '이름(환자이름)'; 
COMMENT ON COLUMN MCARE_USER.LOGIN_FAIL_CNT IS '로그인 실패 횟수'; 
COMMENT ON COLUMN MCARE_USER.PASSWORD_VALUE IS '로그인 암호 (sha-256)'; 
COMMENT ON COLUMN MCARE_USER.REGISTER_DT IS '등록일'; 
COMMENT ON COLUMN MCARE_USER.LOCAL_CIPHER_KEY_VALUE IS '로컬 DB 암호화 키'; 

---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_AGREEMENT 
(	
	AGREEMENT_SEQ 	NUMBER(20,0), 
	AGREEMENT_ORDER NUMBER(*,0), 
	AGREEMENT_NAME 	VARCHAR2(255) NOT NULL, 
	AGREEMENT_CL CLOB NOT NULL,
	AGREEMENT_ID 	VARCHAR2(255 BYTE), 
	TYPE_NAME 		VARCHAR2(255) NOT NULL, 
	VERSION_NUMBER 	NUMBER(20,0), 	
	REQUIRED_YN 	CHAR(1) DEFAULT 'N',
	ENABLED_YN 		CHAR(1) DEFAULT 'N', 
	NEW_YN 			CHAR(1) DEFAULT 'Y', 
	CONSTRAINT PK_AGREEMENT_SEQ PRIMARY KEY (AGREEMENT_SEQ)
); 
CREATE SEQUENCE SEQ_MCARE_AGREEMENT INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;  
COMMENT ON COLUMN MCARE_AGREEMENT.AGREEMENT_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGREEMENT.AGREEMENT_ORDER  IS '동의서 순서'; 
COMMENT ON COLUMN MCARE_AGREEMENT.AGREEMENT_NAME  IS '동의서 이름'; 
COMMENT ON COLUMN MCARE_AGREEMENT.AGREEMENT_CL  IS '동의서 내용';
COMMENT ON COLUMN MCARE_AGREEMENT.AGREEMENT_ID  IS '동의서 식별자 ';
COMMENT ON COLUMN MCARE_AGREEMENT.TYPE_NAME  IS '동의서유형(ALL, MINOR). 현재는 일반/미성년자만 있지만 조만간 외국인도 생길듯하여 NAME으로함';
COMMENT ON COLUMN MCARE_AGREEMENT.VERSION_NUMBER  IS '동의서 버전 ';
COMMENT ON COLUMN MCARE_AGREEMENT.REQUIRED_YN  IS '필수 여부';
COMMENT ON COLUMN MCARE_AGREEMENT.ENABLED_YN IS '활성화 여부';
COMMENT ON COLUMN MCARE_AGREEMENT.REQUIRED_YN IS '필수 여부';
COMMENT ON COLUMN MCARE_AGREEMENT.NEW_YN IS '최신 동의서 여부';
---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_USER_AGREEMENT
(
   USER_AGREEMENT_SEQ   NUMBER (20),
   AGREEMENT_SEQ        NUMBER (20) NOT NULL,
   AGREEMENT_ID			VARCHAR(255) NOT NULL,
   P_ID                 VARCHAR(255) NOT NULL,
   AGREEMENT_YN         CHAR (1) DEFAULT 'N', 
   REGISTER_DT          DATE,
   CONSTRAINT PK_USER_AGREEMENT_SEQ PRIMARY KEY (USER_AGREEMENT_SEQ),
   CONSTRAINT FK_USER_AGREEMENT_SEQ FOREIGN KEY (AGREEMENT_SEQ) REFERENCES MCARE_AGREEMENT(AGREEMENT_SEQ), 
   CONSTRAINT FK_USER_P_ID FOREIGN KEY (P_ID) REFERENCES MCARE_USER(P_ID) 
);
CREATE SEQUENCE SEQ_MCARE_USER_AGREEMENT_UA INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER; 
COMMENT ON COLUMN MCARE_USER_AGREEMENT.USER_AGREEMENT_SEQ IS '시퀀스'; 
COMMENT ON COLUMN MCARE_USER_AGREEMENT.AGREEMENT_SEQ IS '동의서 시퀀스'; 
COMMENT ON COLUMN MCARE_USER_AGREEMENT.AGREEMENT_ID IS '동의서 ID'; 
COMMENT ON COLUMN MCARE_USER_AGREEMENT.P_ID IS '차트번호 (환자번호)'; 
COMMENT ON COLUMN MCARE_USER_AGREEMENT.AGREEMENT_YN IS '동의여부 (Y/N)';
COMMENT ON COLUMN MCARE_USER_AGREEMENT.REGISTER_DT IS '등록일시'; 

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_USER_WITHDRAWAL 
(
   P_ID                VARCHAR2 (255),
   REGISTER_DT         DATE,
   WITHDRAWAL_DT       DATE,
   REASON_VALUE        VARCHAR2 (255)
); 
COMMENT ON TABLE MCARE_USER_WITHDRAWAL IS '사용자 탈퇴 정보'; 
COMMENT ON COLUMN MCARE_USER_WITHDRAWAL.P_ID IS '챠트번호(환자번호)'; 
COMMENT ON COLUMN MCARE_USER_WITHDRAWAL.REGISTER_DT IS '등록일'; 
COMMENT ON COLUMN MCARE_USER_WITHDRAWAL.WITHDRAWAL_DT IS '탈퇴일'; 
COMMENT ON COLUMN MCARE_USER_WITHDRAWAL.REASON_VALUE IS '탈퇴이유'; 


---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_TELNO 
(	
	TELNO_SEQ NUMBER(20,0), 
	BUILDING_DESC VARCHAR2(500), 
	ROOM_DESC VARCHAR2(500), 
	TEL_VALUE VARCHAR2(255), 
	TELNO_ORDER NUMBER(*,0) DEFAULT 1
); 

CREATE SEQUENCE SEQ_MCARE_TELNO_TS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;  
COMMENT ON COLUMN MCARE_TELNO.TELNO_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_TELNO.BUILDING_DESC  IS '건물'; 
COMMENT ON COLUMN MCARE_TELNO.ROOM_DESC  IS '건물내의 방'; 
COMMENT ON COLUMN MCARE_TELNO.TEL_VALUE  IS '전화번호'; 
COMMENT ON COLUMN MCARE_TELNO.TELNO_ORDER  IS '표시순서'; 


---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_HELPER_CONTENTS 
(
	HELPER_SEQ		NUMBER(20, 0), 
	P_ID			VARCHAR2 (255) NOT NULL,
	USER_MSG 		VARCHAR2(4000) NOT NULL, 
	MENU_ID 		VARCHAR2(255), 
	SEND_DT 		DATE DEFAULT SYSDATE,
	
); 
CREATE INDEX IDX_HELPER_CONTENTS ON MCARE_HELPER_CONTENTS(P_ID, SEND_DT); 
CREATE SEQUENCE SEQ_MCARE_HELPER_HS INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;  
COMMENT ON COLUMN MCARE_HELPER_CONTENTS.HELPER_SEQ  IS '시퀀스';
COMMENT ON COLUMN MCARE_HELPER_CONTENTS.P_ID  IS '환자번호 (검색용)';
COMMENT ON COLUMN MCARE_HELPER_CONTENTS.USER_MSG  IS '도우미 화면에 보일 메시지';
COMMENT ON COLUMN MCARE_HELPER_CONTENTS.MENU_ID  IS '어느 메뉴에 붙는지 메뉴 ID (분석용)';
COMMENT ON COLUMN MCARE_HELPER_CONTENTS.SEND_DT  IS '보낸시간. Push를 통해서는 전송실패되었을 수 있으나 어쨌든 서버는 보낸 메시지';


-- PUSH 메시지 추적을 위한 맵핑 테이블 
CREATE TABLE MCARE_MNS_MSGMAPPING 
(
	P_ID			VARCHAR2 (255) NOT NULL,
	CONTENTS_SEQ 	NUMBER(20,0) NOT NULL,
	FORM_ID			VARCHAR2(255) NOT NULL, 	
	MESSAGE_VALUE 	VARCHAR2(255) NOT NULL,
	LOG_DT			DATE DEFAULT SYSDATE 
); 
CREATE INDEX IDX_MSGMAPPING_CONTENTS ON MCARE_MNS_MSGMAPPING(P_ID); 
COMMENT ON COLUMN MCARE_MNS_MSGMAPPING.P_ID  IS '환자번호 (검색용)';
COMMENT ON COLUMN MCARE_MNS_MSGMAPPING.CONTENTS_SEQ  IS 'PUSH 메시지 구분자';
COMMENT ON COLUMN MCARE_MNS_MSGMAPPING.FORM_ID  IS '메시지 유형';
COMMENT ON COLUMN MCARE_MNS_MSGMAPPING.MESSAGE_VALUE  IS '메시지 본문 내용';
COMMENT ON COLUMN MCARE_MNS_MSGMAPPING.LOG_DT  IS '로그 남기는 시간';



---------------------------------------------------------------------------------------------- 
--- 중간 테이블 
--- 간호요청 
CREATE TABLE MCARE_INF_NURSE (
  NURSE_SEQ      NUMBER (20),
  P_ID           VARCHAR2 (255),
  REQ_CODE_VALUE VARCHAR2(255), 
  REQ_VALUE     VARCHAR2(255),
  REQ_ETC_VALUE VARCHAR2(255), 
  REG_DT        DATE DEFAULT SYSDATE, 
  UPDATE_DT     DATE, 
  RECEIVE_DT	DATE 
); 
CREATE SEQUENCE SEQ_MCARE_IF_NURSE_SEQ INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_INF_NURSE.NURSE_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_INF_NURSE.P_ID  IS '환자번호'; 
COMMENT ON COLUMN MCARE_INF_NURSE.REQ_CODE_VALUE  IS '요청코드나열 (화면에서 사용하기 편한 형태로)'; 
COMMENT ON COLUMN MCARE_INF_NURSE.REQ_VALUE  IS '요청을 문자료 표시 (부산대 요구사항)'; 
COMMENT ON COLUMN MCARE_INF_NURSE.REQ_ETC_VALUE  IS '주관식 요청 '; 
COMMENT ON COLUMN MCARE_INF_NURSE.REG_DT  IS '요청일과 시간'; 
COMMENT ON COLUMN MCARE_INF_NURSE.UPDATE_DT  IS '기간계에서 요청을 가져간 시간'; 
COMMENT ON COLUMN MCARE_INF_NURSE.RECEIVE_DT IS '간호에서 요청을 접수한 시간. 부산대에서 요구하니까 추가는 해주는데 과연 값이 제대로 들어올 것인가 의심하고 있음'; 


-- PUSH로 나갈 메시지의 형식 
CREATE TABLE MCARE_PUSH_FORM (
	FORM_ID 			VARCHAR2(255), 
	FORM_TYPE			VARCHAR2(50), 
	USE_YN				CHAR(1), 
	MENU_ID				VARCHAR2(255),
	INCLUDE_NAME_YN 	CHAR(1), 
	FORM_DESC			VARCHAR2(500),
	REG_DT				DATE DEFAULT SYSDATE,  
	CONSTRAINT PK_MCARE_PUSH_FORM PRIMARY KEY (FORM_ID), 
	CONSTRAINT FK_PUSH_FORM_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES MCARE_MENU (MENU_ID)
); 
COMMENT ON COLUMN MCARE_PUSH_FORM.FORM_ID  IS '메시지 형식에 대한 식별자'; 
COMMENT ON COLUMN MCARE_PUSH_FORM.FORM_TYPE  IS '유형 : PAGE, MAP, GUIDE';
COMMENT ON COLUMN MCARE_PUSH_FORM.USE_YN	 IS '사용여부 (PUSH_MSG쪽에서 FK로 참조될꺼라서 삭제기능이 없을것임)'; 
COMMENT ON COLUMN MCARE_PUSH_FORM.MENU_ID	 IS '유형이 PAGE인 경우 메뉴 식별자. 확장자가 page인 메뉴만 가능'; 
COMMENT ON COLUMN MCARE_PUSH_FORM.INCLUDE_NAME_YN	 IS '메시지에 이름포함 여부'; 
COMMENT ON COLUMN MCARE_PUSH_FORM.FORM_DESC  IS '형식에 대한 설명';
COMMENT ON COLUMN MCARE_PUSH_FORM.REG_DT  IS '추가된 시간';

-- PUSH로 전송될 메시지 
CREATE TABLE MCARE_INF_PUSH_MSG ( 
	PUSH_SEQ		NUMBER(20), 
	FORM_ID			VARCHAR2(255) NOT NULL, 
	HOSPITAL_VALUE  VARCHAR2(255), 
	P_ID			VARCHAR2(255) NOT NULL, 
	P_NAME			VARCHAR2(255), 
	MESSAGE_VALUE 	VARCHAR2(255) NOT NULL,
	PARAM_VALUE		VARCHAR2(255), 
	STAGE_ORDER 	NUMBER(2) NOT NULL DEFAULT 40, 
	REQ_DT			DATE DEFAULT SYSDATE, 
	SENDER_ID 		VARCHAR2(255) DEFAULT 'UNKNOWN', 
	PUMPING_DT		DATE, 
	SEND_YN			CHAR(1) DEFAULT 'N', 
	RESERVE_SEND_DT DATE DEFAULT SYSDATE 
); 
CREATE SEQUENCE SEQ_MCARE_INF_FORM_PUSH_PS INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.PUSH_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.FORM_ID  IS '[기간계] 메시지 형식 (DB가 달라서 FK를 걸어둘 수 없음)'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.HOSPITAL_VALUE  IS '[기간계] 어느병원에서 쏘는 메시지인지 구분. 이 병원에 등록된 FORM_ID 대로 PUSH가 나갈것임'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.P_ID  	IS '[기간계] 메시지 수신자'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.P_NAME  IS '[기간계/옵션] 메시지 수신자 이름'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.MESSAGE_VALUE  IS '[기간계] 메시지 내용'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.PARAM_VALUE  IS '[기간계/옵션] 메시지 형식이 필요로 하는 파라미터. 예) MAP-목적지 (옵션)'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.STAGE_ORDER  IS '[기간계/필수] 접수(10)-진료(20)-수납(30)-귀가(40).'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.SENDER_ID  IS '[기간계/옵션] 누가 메시지 전송을 의뢰했는지 확인용'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.REQ_DT  IS '전송 요청시간'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.PUMPING_DT  IS '요청을 꺼낸시간'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.SEND_YN  IS '전송의뢰 성공여부'; 
COMMENT ON COLUMN MCARE_INF_PUSH_MSG.RESERVE_SEND_DT IS '[기간계/옵션] 예약전송시간'; 


-- MAP 
CREATE TABLE MCARE_POI_MAPPING (
	POI_SEQ NUMBER(20), 
	LEGACY_NAME VARCHAR2(255), 
	MAP_NAME VARCHAR2(255), 
	MAPPING_DESC VARCHAR2(500),
	REG_DT DATE DEFAULT SYSDATE,
	USE_YN CHAR(1) DEFAULT 'N'
); 
CREATE SEQUENCE SEQ_MCARE_POI_PS INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_POI_MAPPING.POI_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_POI_MAPPING.LEGACY_NAME  IS '기간계 이름'; 
COMMENT ON COLUMN MCARE_POI_MAPPING.MAP_NAME  IS '지도상의 이름'; 
COMMENT ON COLUMN MCARE_POI_MAPPING.MAPPING_DESC  IS '관리를 위한 설명'; 
COMMENT ON COLUMN MCARE_POI_MAPPING.REG_DT  IS '등록시간'; 
COMMENT ON COLUMN MCARE_POI_MAPPING.USE_YN  IS '사용여부'; 


-- BEACON EVENT LOG 
CREATE TABLE MCARE_EVENT_LOG (
	LOG_SEQ NUMBER(20) DEFAULT 0, 
	P_ID 	VARCHAR2 (255),
---	DEVICE_UUID_ID VARCHAR2(255), 
	EVENT_NAME VARCHAR2(255) NOT NULL, 
	LOG_DT DATE DEFAULT SYSDATE 
); 
CREATE SEQUENCE SEQ_MCARE_EVENT_LOG_LS INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_EVENT_LOG.LOG_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_EVENT_LOG.P_ID  IS '환자번호 (NULL일 수 있음)'; 
--- COMMENT ON COLUMN MCARE_EVENT_LOG.DEVICE_UUID_ID  IS '토큰ID (NULL일 수 있음)'; 
COMMENT ON COLUMN MCARE_EVENT_LOG.EVENT_NAME  IS '이벤트 이름'; 
COMMENT ON COLUMN MCARE_EVENT_LOG.LOG_DT  IS '이벤트 수신 시간 (발생시간이 아님)';

-- 비콘 이벤트 집계 
CREATE TABLE MCARE_AGG_EVENT (
	AGG_SEQ NUMBER(20) DEFAULT 0, 
	EVENT_NAME VARCHAR2(255) NOT NULL, 
	HIT_CNT NUMBER(*,0), 
	AGG_DT DATE DEFAULT SYSDATE 
); 
CREATE SEQUENCE SEQ_MCARE_AGG_EVENT_AS INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_AGG_EVENT.AGG_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_EVENT.EVENT_NAME  IS '발생된 이벤트명'; 
COMMENT ON COLUMN MCARE_AGG_EVENT.HIT_CNT  IS '발생횟수'; 
COMMENT ON COLUMN MCARE_AGG_EVENT.AGG_DT  IS '집계기준시간'; 
 
-- push 집계 
CREATE TABLE MCARE_AGG_MSG (
	AGG_SEQ NUMBER(20) DEFAULT 0, 
	AGG_DT DATE DEFAULT SYSDATE, 
	TOTAL_CNT NUMBER(*, 0), 
	SUCCESS_CNT NUMBER(*, 0)
); 
CREATE SEQUENCE SEQ_MCARE_AGG_MSG_MS INCREMENT BY 1 START WITH 1 NOORDER; 
COMMENT ON COLUMN MCARE_AGG_MSG.AGG_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_MSG.AGG_DT  IS '집계날짜'; 
COMMENT ON COLUMN MCARE_AGG_MSG.TOTAL_CNT  IS '전송횟수'; 
COMMENT ON COLUMN MCARE_AGG_MSG.SUCCESS_CNT  IS '성공횟수'; 

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_AGG_USER_AGE 
(
	AGG_SEQ 	NUMBER(20, 0), 
	AGE_ORDER 	NUMBER(*, 0), 
	DATA_CNT 	NUMBER(*,0), 
	AGG_DT 		DATE
); 
CREATE SEQUENCE SEQ_MCARE_AGG_USER_AU INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_AGG_USER_AGE.AGG_SEQ IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_USER_AGE.AGE_ORDER IS '연령대'; 
COMMENT ON COLUMN MCARE_AGG_USER_AGE.DATA_CNT IS '인원수'; 
COMMENT ON COLUMN MCARE_AGG_USER_AGE.AGG_DT IS '통계일시'; 
---------------------------------------------------------------------------------------------- 

CREATE TABLE MCARE_AGG_USER_TMP --- 사용자 연령대와 우편번호 통계데이터 마련을 위한 임시 테이블. 지우고, 데이터 추가  
(
	AGE_ORDER 	NUMBER(*, 0), 
	POSTNO_VALUE VARCHAR2(255) 
); 
COMMENT ON COLUMN MCARE_AGG_USER_TMP.AGE_ORDER IS '연령대'; 
COMMENT ON COLUMN MCARE_AGG_USER_TMP.POSTNO_VALUE IS '우편번호'; 
commit; 

---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_AGG_USER_POSTNO 
(
	AGG_SEQ 		NUMBER(20, 0) NOT NULL, 
	POSTNO_VALUE	VARCHAR2(255) NOT NULL, 
	DATA_CNT 		NUMBER(*, 0) NOT NULL, 
	AGG_DT			DATE NOT NULL  
); 
CREATE SEQUENCE SEQ_MCARE_AGG_POSTNO_AP INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_AGG_USER_POSTNO.AGG_SEQ IS '시퀀스'; 
COMMENT ON COLUMN MCARE_AGG_USER_POSTNO.POSTNO_VALUE IS '우편번호에 해당하는 시 정보'; 
COMMENT ON COLUMN MCARE_AGG_USER_POSTNO.DATA_CNT IS '인원수'; 
COMMENT ON COLUMN MCARE_AGG_USER_POSTNO.AGG_DT IS '통계일시'; 
---------------------------------------------------------------------------------------------- 
CREATE TABLE MCARE_ZIPCODE 
(
	ZIP_SEQ NUMBER(20, 0) DEFAULT 0, 
	ZIP_ID VARCHAR2(255) NOT NULL, 
	SI_ID VARCHAR2(255) NOT NULL, 
	SI_VALUE VARCHAR2(255) NOT NULL, 
	GUNGU_VALUE VARCHAR2(255) 
); 
CREATE SEQUENCE SEQ_MCARE_ZIPCODE_ZC INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NOORDER;
COMMENT ON COLUMN MCARE_ZIPCODE.ZIP_SEQ  IS '시퀀스'; 
COMMENT ON COLUMN MCARE_ZIPCODE.ZIP_ID  IS '시군구우편번호 (5자리체계에서 앞에 3자리)'; 
COMMENT ON COLUMN MCARE_ZIPCODE.SI_ID  IS '시군구우편번호 (5자리체계에서 앞에 2자리)'; 
COMMENT ON COLUMN MCARE_ZIPCODE.SI_VALUE  IS '시'; 
COMMENT ON COLUMN MCARE_ZIPCODE.GUNGU_VALUE  IS '군/구'; 


--- logback script : https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/resources/ch/qos/logback/classic/db/script/oracle.sql